//administracion
export const GET_PRODUCTOS_SUCCESS = 'GET_PRODUCTOS_SUCCESS';
export const GET_PRODUCTOS_FAIL = 'GET_PRODUCTOS_FAIL';

export const AGREGAR_PRODUCTO_SUCCESS = 'AGREGAR_PRODUCTO_SUCCESS';
export const AGREGAR_PRODUCTO_FAIL = 'AGREGAR_PRODUCTO_FAIL';

export const ELIMINAR_PRODUCTO_SUCCESS = 'AGREGAR_PRODUCTO_SUCCESS';
export const ELIMINAR_PRODUCTO_FAIL = 'AGREGAR_PRODUCTO_FAIL';

export const GET_PRODUCTOS_DE_MARCA_SUCCESS = 'GET_PRODUCTOS_DE_MARCA_SUCCESS';
export const GET_PRODUCTOS_DE_MARCA_FAIL = 'GET_PRODUCTOS_DE_MARCA_FAIL';

export const GET_INVENTARIO_SUCCESS = 'GET_INVENTARIO_SUCCESS';
export const GET_INVENTARIO_FAIL = 'GET_INVENTARIO_FAIL';

export const GET_SOCIOS_SUCCESS = 'GET_SOCIOS_SUCCESS';
export const GET_SOCIOS_FAIL = 'GET_SOCIOS_FAIL';

export const GET_GANANCIAS_NETAS_SUCCESS = 'GET_GANANCIAS_NETAS_SUCCESS';
export const GET_GANANCIAS_NETAS_FAIL = 'GET_GANANCIAS_NETAS_FAIL'

export const GET_CAJA_SUCCESS = 'GET_CAJA_SUCCESS';
export const GET_CAJA_FAIL = 'GET_CAJA_FAIL';

export const GET_PRODUCTOS_LIST_SUCCESS = 'GET_PRODUCTOS_SUCCESS'; 
export const GET_PRODUCTOS_LIST_FAIL = 'GET_PRODUCTOS_FAIL';

export const GET_CATEGORIAS_SUCCESS = 'GET_CATEGORIAS_SUCCESS';
export const GET_CATEGORIAS_FAIL = 'GET_CATEGORIAS_FAIL';
export const GET_MARCAS_SUCCESS = 'GET_MARCAS_SUCCESS';
export const GET_MARCAS_FAIL = 'GET_MARCAS_FAIL';

export const GET_CAJERA_PAGINATION_COUNT_SUCCESS = 'GET_CAJERA_PAGINATION_COUNT_SUCCESS';
export const GET_CAJERA_PAGINATION_COUNT_FAIL = 'GET_CAJERA_PAGINATION_COUNT_FAIL';

export const GET_CAJERA_PAGINATION_NEXT_SCCESS = 'GET_CAJERA_PAGINATION_NEXT_SUCCESS';
export const GET_CAJERA_PAGINATION_NEXT_FAIL = 'GET_CAJERA_PAGINATION_NEXT_FAIL';

export const GET_CAJERA_PAGINATION_PREVIUS_SUCCESS = 'GET_CAJERA_PAGINATION_PREVIUS_SUCCESS';
export const GET_CAJERA_PAGINATION_PREVIUS_FAIL = 'GET_CAJERA_PAGINATION_PREVIUS_FAIL';

export const GET_CAJERA_PAGINATION_RESULTS_SUCCESS = 'GET_CAJERA_PAGINATION_RESULTS_SUCCESS';
export const GET_CAJERA_PAGINATION_RESULTS_FAIL = 'GET_CAJERA_PAGINATION_RESULTS_FAIL';
